---
title: "Mini-Project 2"
author: "Natalia Iannucci and Hana Hirano"
date: "2019-03-24"
output: 
  html_document:
    code_folding: show
---

## Loading the data

```{r, message = FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

Filter for the variables that we will examine
```{r}
contribution_data <- select(contributions, transaction_type, transaction_amt, cand_id, state)
house_election_data <- select(house_elections, fec_id, party, ge_winner)
```

Join datasets to get contribution and election data together
```{r, message = FALSE}
contributions_to_elections <- contribution_data %>%
  inner_join(house_election_data, by = c("cand_id" = "fec_id")) %>%
  filter(transaction_type %in% c("24K", "24E")) %>%
  filter(party %in% c("D", "R")) %>%
  group_by(state)
```

Look at total transactions per state to determine which states have the most transactions to use in analysis
```{r}
contributions_to_elections %>%
  group_by(state) %>%
  summarize(total_transactions = sum(transaction_amt)) %>%
  arrange(desc(total_transactions))
```

```{r}
ggplot(contributions_to_elections, aes(x = party, y = transaction_amt)) +
  geom_bar(stat = "identity", aes(fill = transaction_type), position = "dodge") +
  scale_y_continuous(limits, breaks, labels) +
  xlab("Political Party") +
  ylab("Transactions A")
  facet_wrap(~ state)
```

> Word count: `r wordcountaddin::word_count()`


